server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product-service
  datasource:
    driveClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product?characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: root1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
